    drop table if exists fs_user;

    create table fs_user (
       	id bigint generated by default as identity,
        username varchar(255) not null unique,
        name varchar(64),
        password varchar(255),
        remember boolean
    );
